services:
  - type: web
    name: oakter-inventory-backend
    env: node
    buildCommand: npm install && npm run install-backend
    startCommand: npm run start-backend
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    healthCheckPath: /api/health
    autoDeploy: true 